#!/usr/bin/env bash

docker -v > /dev/null
docker_exit_code=$?

if [[ $docker_exit_code != 0 ]]; then
  echo 'It appears that docker is not installed or in PATH'
  echo 'Please install docker or add it to PATH'
  exit $docker_exit_code
fi

if [[ "$@" = '' ]] ; then
  echo 'Please specify a data directory for soloii'
  exit 1
fi

lrose_host_data_dir=$1

lrose_dockerhost=$(docker info | grep Name | sed -e 's/Name: //')

#
# use architecture-specific method to determine ip
#

get_ip_address () {
  lrose_uname=$(uname)
  if [[ $lrose_uname = 'Darwin' ]]; then
    echo $(ifconfig | grep "inet " | grep -Fv 127.0.0.1 | awk '{print $2}' |head -1)
  elif [[ $lrose_uname = 'Linux' ]]; then
    echo $(hostname -I)
  else
    echo TODO
    exit 1
  fi
}

lrose_host_ip=$(get_ip_address)

xhost + $lrose_dockerhost

docker run \
  -e DISPLAY=$lrose_host_ip:0 \
  -v /tmp/.X11-unix:/tmp/.X11-unix \
  -v $lrose_host_data_dir:/data \
  ncareol/lrose-soloii /data
